name: effective-py
dependencies:
- certifi=14.05.14=py27_0
- ipython=3.1.0=py27_1
- ipython-notebook=3.1.0=py27_1
- jinja2=2.7.3=py27_1
- jsonschema=2.4.0=py27_0
- libsodium=0.4.5=0
- markupsafe=0.23=py27_0
- mistune=0.5.1=py27_1
- openssl=1.0.1k=1
- pip=7.0.3=py27_0
- ptyprocess=0.4=py27_0
- pygments=2.0.2=py27_0
- python=2.7.10=0
- python.app=1.2=py27_3
- pyzmq=14.6.0=py27_0
- readline=6.2=2
- setuptools=17.0=py27_0
- sqlite=3.8.4.1=1
- ssl_match_hostname=3.4.0.2=py27_0
- terminado=0.5=py27_0
- tk=8.5.18=0
- tornado=4.2=py27_0
- zeromq=4.0.5=0
- zlib=1.2.8=0
- pip:
  - backports.ssl-match-hostname==3.4.0.2
